### ISSUE TITLE
One-button-run-all

### ISSUE THREAD

**Issue by MasterVexillen** [rosalindfranklininstitute/Ot2Rec#30]
### Overview
-  It would be good to have a one-button-run-all option for each workflow, using default O2R setting
-  There is one o2r.runall command for IMOD workflow, but probably obsolete --- needs updating

### To-do
- [ ] Add o2r.runall.\<workflow\> for each workflow
- [ ] Update o2r.runall --> o2r.runall.imod
- [ ] Automate calculation of default patch sizes for patch tracking
