### ISSUE TITLE
Workflow diagram generator

### ISSUE THREAD

**Issue by elainehoml** [rosalindfranklininstitute/Ot2Rec#39]
# Overview

Generate a workflow diagram from the metadata files to show the processes that o2r has completed.

# To-do

- [ ] Show processes, metadata for each process and the files generated
- [ ] Quality metrics (dependent on quality metrics plugin #41)
- [ ] (optional) report time taken for each step, machine stats
- [ ] citations (#42)

**Comment by MasterVexillen** [comment]
Could be closed - an issue in the separate report repo and it's working
