### ISSUE TITLE
Quality metric plugin

### ISSUE THREAD

**Issue by elainehoml** [rosalindfranklininstitute/Ot2Rec#41]
# Overview

Plugin to measure and output quality metrics for each step as a performance indicator.

# To-do

- [ ] Final reconstruction -> FRC/FSC e/o
- [ ] Any stage -> FRC/FSC checkerboard local resolution
- [ ] Alignment -> Alignment errors from IMOD/AreTomo
- [ ] Motioncor -> Motion correction errors?
