### ISSUE TITLE
Citations generator

### ISSUE THREAD

**Issue by elainehoml** [rosalindfranklininstitute/Ot2Rec#42]
# Overview

Plugin to generate citations at each step. 

# To-do

- [ ] Generate citations from MotionCor
- [ ] Generate citations from IMOD
- [ ] Generate citations from AreTomo
- [ ] Generate citations from Savu (Already part of Savu, just need to port that function over)
- [ ] Generate citations from ctffind4
- [ ] Generate citations from RedLionFish

**Comment by MasterVexillen** [comment]
I think this can be closed now -
1. citations are now in the report repo
2. they are outputting correctly at the moment
