### ISSUE TITLE
Investigate MagicGUI for O2R

### ISSUE THREAD

**Issue by MasterVexillen** [rosalindfranklininstitute/Ot2Rec#43]
## Overview
To investigate the use of MagicGUI for the creation of YAML files, with idea of replacing current Python argparse feature.

## To-do list
- [x] MagicGUI \@ project creation
- [x] MagicGUI \@ MC
- [x] MagicGUI \@ CTFFind
- [x] MagicGUI \@ IMOD align
- [x] MagicGUI \@ IMOD recon
- [x] MagicGUI \@ IMOD align (external)
- [x] MagicGUI \@ CTFSim
- [x] MagicGUI \@ Savu recon
- [x] MagicGUI \@ RLDeconv
- [x] MagicGUI \@ Aretomo
